### ISSUE TITLE
failed: Module did not self-register

### ISSUE THREAD

**Issue by YaduAhuja** [microsoft/vscode-windows-process-tree#32]
I am Building an Extension for VSCode and whenever I try to call the `getProcessTree` method I get the below error.
I have tried creating a new extension but the error remains the same.
I have also installed node again.

Error: 
`failed: Module did not self-register: '\\?\d:\Github\Test-extension\test\node_modules\windows-process-tree\build\Release\windows_process_tree.node`

Node version's tested: 16.3.0 & 14.17.1
Windows Build Version: 19043.1081

**Comment by Tyriar** [comment]
I'm guessing this is happening because you compiled the module on a different version of node to what the VS Code extension host is running?

**Comment by nturinski** [comment]
Hi @Tyriar, I was running into this same issue and I don't think it's due to compiling on a different version of node.

I've rebuilt the project on v16.17.1 and ran `npm install` after removing `node_modules` to ensure everything was built on the same version. I also matched the version that VS Code is running though based off what you said, it should only have to be the same version of node that the VS Code extension was built on?

Any idea on how I could resolve this?

I've tried `npm install` in an administrator PowerShell terminal as well.

![image](https://github.com/microsoft/vscode-windows-process-tree/assets/5290572/eeed86f1-27ec-43e9-b253-c1dfbc519c22)

**Comment by Tyriar** [comment]
That's what the "Module did not self-register" error seems to mean. @rzhao271 any thoughts?

**Comment by nturinski** [comment]
Yeah, I haven't been able to find anything else in my search to resolve this.

Do you have a configuration that uses `windows-process-tree` that I could reference? I'm wondering if there needs to be a very specific version of Visual Studio C++ Desktop tools for specific versions of Node.js or something.

**Comment by rzhao271** [comment]
Hi @nturinski, does the issue still reproduce with v0.5.0 of the package?
The microsoft/vscode repository uses the package, but I'm not aware of a requirement to have a specific version of C++ build tools installed. However, I'm wondering which version of node-gyp you're using? I'm able to compile the package on Windows 11 using node-gyp 8.0.0.

CC @deepak1556
