### ISSUE TITLE
Give full executable path for processes

### ISSUE THREAD

**Issue by rianadon** [Microsoft/vscode-windows-process-tree#7]
First of all, this really speeds up the terminal title updates. Great job!

However, each process's `name` contains only the basename of the executable. For Microsoft/vscode#31234, I need the full path to the executable.

The [documention](https://msdn.microsoft.com/en-us/library/windows/desktop/ms684839.aspx) recommends querying modules to give the full executable path, rather than querying programs. However it seems that would require special logic to handle both 32 bit and 64 bit programs. Retrieving the program's name from its executable might also work (maybe have a function attached to each program result?), given that in the context of the PR I only need the full executable of one program.

**Comment by Tyriar** [comment]
@rianadon Nice find.

When we were looking into this @the-ress pointed out that this method is flawed as well. While you found the `start cmd` problem and the conhost workaround, it turns out that this is an issue with any program, eg. `start notepad` will return notepad as the name.

A better approach would likely be to use `AttachConsole` and `GetConsoleProcessList` which apparently correctly gives the right foreground process (I haven't tried it out yet). This should probably live in either winpty or node-pty as then we could modify the node-pty `process` API to be async and work on both Unix and Windows. Prototype: https://github.com/Tyriar/node-pty/compare/master...the-ress:get_process_list

**Comment by rianadon** [comment]
I tested out the branch and it seems to work great. It still gives just the executable name but I'll wait for the prototype to become official before creating any new issues.

**Comment by Tyriar** [comment]
Also:

- https://docs.microsoft.com/en-us/windows/console/getconsoletitle
- https://docs.microsoft.com/en-us/windows/console/getconsoleoriginaltitle
